name: Say Hi
run-name: Saying hello
on:
  issues:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: create new branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'issue-${{ github.event.issue.number }}'
      - name: setup julia env
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
          arch: 'default'
      - name: execute script
        run: |
          julia test_script.jl
          touch wowzers.txt
      - name: create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Update catalog from issue #${{ github.event.issue.number }}'